"""Add Story model

Revision ID: 67687d1b6b04
Revises: 88402b5f2acf
Create Date: 2020-11-12 01:16:29.814170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67687d1b6b04'
down_revision = '88402b5f2acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('story')
    # ### end Alembic commands ###
