"""Add Story model

Revision ID: 88402b5f2acf
Revises: 6a8a294ef3f5
Create Date: 2020-11-12 01:11:41.231047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88402b5f2acf'
down_revision = '6a8a294ef3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
